### ISSUE TITLE
npm run build有error

### ISSUE THREAD

**Issue by xxyjskx1987** [vanishcode/iview2-management-system#2]
Unexpected token punc «(», expected punc «:»
请问如何解决

**Comment by Leega0** [comment]
我觉得如果是学习的话，自己一步步搭建，其中不懂的来参考下实现会更好，毕竟iview2也只是组件库。

**Comment by 547437352** [comment]
作者你好！非常感谢你的贡献，进期正好要做后台系统，厌烦了以前的模式，想引进新技术！首先说下我是小白，如果提的问题是iview或者vue本身的问题请谅解：
1.当我点击浏览器回退按钮的时候，确实回到了上一个页面，但是侧边栏选中的却还是不变，没有选中相应的按钮！
2.当我在侧边栏切换的时候发现js实际上执行了一次！如我在form组件中console.log(123123)，发现只有当进入主页面的时候执行一次，但是再次切换到form组件不会执行！

再次重申：我是小白，我是小白，我是小白，我只是提出自己的疑惑！

**Comment by vanishcode** [comment]
’npm build error‘和导航栏问题已修复。感谢支持。
