### ISSUE TITLE
build 失败

### ISSUE THREAD

**Issue by ericdai** [vanishcode/iview2-management-system#6]
C:\working\iview2-management-system>npm run build

> by_iview2.0@1.0.0 build C:\working\iview2-management-system
> node build/build.js

- building for production...
Starting to optimize CSS...
Processing static/css/app.5a96421ea17a8dd951b0df4f6bd93bef.css...
Processed static/css/app.5a96421ea17a8dd951b0df4f6bd93bef.css, before: 258111, after: 241209, ratio: 93.45%
Hash: ca359ab24e3ebca9265f
Version: webpack 2.3.1
Time: 157009ms
                                                  Asset       Size  Chunks                    Chunk Names
    static/css/app.5a96421ea17a8dd951b0df4f6bd93bef.css     241 kB      12  [emitted]         app
                      static/fonts/ionicons.2c2ae06.eot     121 kB          [emitted]
                      static/fonts/ionicons.24712f6.ttf     189 kB          [emitted]
                     static/fonts/ionicons.05acfdb.woff    67.9 kB          [emitted]
                   static/img/brown-papersq.82cd9f5.png    18.2 kB          [emitted]
                    static/js/0.152a36f242acd7804f2a.js     574 kB       0  [emitted]  [big]
                    static/js/1.fbb1a380de00b559bf7f.js     835 kB       1  [emitted]  [big]
                    static/js/2.02e3e0f962f331c53550.js    1.14 kB       2  [emitted]
                    static/js/3.7129edf1d524aac661a5.js     1.1 kB       3  [emitted]
                    static/js/4.08c8ff1759cd39f2df84.js    9.82 kB       4  [emitted]
                    static/js/5.3696cd6841d75bf8efb0.js    7.26 kB       5  [emitted]
                    static/js/6.43447ced1001be6d7180.js    6.14 kB       6  [emitted]
                    static/js/7.0b2f58a77a0a9773bc8c.js    11.5 kB       7  [emitted]
                    static/js/8.de441d249d8d46b4674f.js    2.72 kB       8  [emitted]
                    static/js/9.49003fa26fff8877b522.js    3.26 kB       9  [emitted]
                   static/js/10.e193e9128ba584db3885.js  716 bytes      10  [emitted]
               static/js/vendor.51987875f1e095ae2c41.js    1.73 MB      11  [emitted]  [big]  vendor
                  static/js/app.ca87d83640af8b624e2b.js    76.7 kB      12  [emitted]         app
                   static/js/13.ed1fb78296e7f2d41bbc.js     722 kB      13  [emitted]  [big]  highlight
             static/js/manifest.b1b46fe076840e2cf85c.js     1.8 kB      14  [emitted]         manifest
                        static/img/ionicons.621bd38.svg     334 kB          [emitted]  [big]
                static/js/0.152a36f242acd7804f2a.js.map     717 kB       0  [emitted]
                static/js/1.fbb1a380de00b559bf7f.js.map     976 kB       1  [emitted]
                static/js/2.02e3e0f962f331c53550.js.map    10.9 kB       2  [emitted]
                static/js/3.7129edf1d524aac661a5.js.map    11.1 kB       3  [emitted]
                static/js/4.08c8ff1759cd39f2df84.js.map    17.9 kB       4  [emitted]
                static/js/5.3696cd6841d75bf8efb0.js.map    11.5 kB       5  [emitted]
                static/js/6.43447ced1001be6d7180.js.map    11.2 kB       6  [emitted]
                static/js/7.0b2f58a77a0a9773bc8c.js.map    21.6 kB       7  [emitted]
                static/js/8.de441d249d8d46b4674f.js.map    16.9 kB       8  [emitted]
                static/js/9.49003fa26fff8877b522.js.map    6.01 kB       9  [emitted]
               static/js/10.e193e9128ba584db3885.js.map    4.97 kB      10  [emitted]
           static/js/vendor.51987875f1e095ae2c41.js.map    8.38 MB      11  [emitted]         vendor
              static/js/app.ca87d83640af8b624e2b.js.map     117 kB      12  [emitted]         app
static/css/app.5a96421ea17a8dd951b0df4f6bd93bef.css.map     352 kB      12  [emitted]         app
               static/js/13.ed1fb78296e7f2d41bbc.js.map     2.3 MB      13  [emitted]         highlight
         static/js/manifest.b1b46fe076840e2cf85c.js.map    15.2 kB      14  [emitted]         manifest
                                             index.html  452 bytes          [emitted]
                              static/screenshots/s2.png    46.8 kB          [emitted]
                              static/screenshots/s3.png    26.2 kB          [emitted]
                              static/screenshots/s1.png     120 kB          [emitted]

ERROR in static/js/0.152a36f242acd7804f2a.js from UglifyJs
Unexpected token punc «(», expected punc «:» [static/js/0.152a36f242acd7804f2a.js:10691,19]

ERROR in static/js/1.fbb1a380de00b559bf7f.js from UglifyJs
Unexpected token punc «(», expected punc «:» [static/js/1.fbb1a380de00b559bf7f.js:68,8]

ERROR in static/js/4.08c8ff1759cd39f2df84.js from UglifyJs
Unexpected token punc «(», expected punc «:» [static/js/4.08c8ff1759cd39f2df84.js:101,8]

ERROR in static/js/5.3696cd6841d75bf8efb0.js from UglifyJs
Unexpected token: punc ()) [static/js/5.3696cd6841d75bf8efb0.js:72,11]

ERROR in static/js/6.43447ced1001be6d7180.js from UglifyJs
Unexpected token punc «(», expected punc «:» [static/js/6.43447ced1001be6d7180.js:84,8]

ERROR in static/js/7.0b2f58a77a0a9773bc8c.js from UglifyJs
Unexpected token punc «(», expected punc «:» [static/js/7.0b2f58a77a0a9773bc8c.js:180,8]

ERROR in static/js/9.49003fa26fff8877b522.js from UglifyJs
Unexpected token punc «(», expected punc «:» [static/js/9.49003fa26fff8877b522.js:32,8]

ERROR in static/js/app.ca87d83640af8b624e2b.js from UglifyJs
Unexpected token: operator (>) [./src/router/index.js:13,23][static/js/app.ca87d83640af8b624e2b.js:1436,28]

  Build complete.

  Tip: built files are meant to be served over an HTTP server.
  Opening index.html over file:// won't work.

**Comment by vanishcode** [comment]
已修复。感谢支持。
